name: upfromgede

on: workflow_dispatch

permissions:
  contents: write

jobs:
  upload:
    runs-on: ubuntu-latest

    env:
      REPO: ${{ github.repository }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install gdown pyyaml

      - name: Run upload script
        run: |
          python upload_releases.py
